import './styles.css';
import { companionValues, cvToFrequency, frequencyToNoteName, jitteredInterval, quantizeCv, sampleHold, slew, trackHold, type HoldMode } from './model';

type Source='lfo'|'noise'|'manual';
type Point={input:number;raw:number;output:number;high:number;low:number;event:boolean;gate:boolean};
type Voice={osc:OscillatorNode;gain:GainNode;pan:StereoPannerNode|null};
type VoiceName='low'|'centre'|'high';

const app=document.querySelector<HTMLDivElement>('#app');
if(!app)throw new Error('App root not found');
app.innerHTML=`
<header class="topbar"><div><p class="eyebrow">Interactive CV learning laboratory</p><h1>Sample & Hold Lab</h1></div><div class="mode-tabs"><button id="learnTab" class="active">Learn</button><button id="exploreTab">Explore</button></div></header>
<p class="mission">See, measure and hear how changing voltages become sampled, held, tracked, slewed and converted to musical pitch.</p>
<section id="lessonPanel" class="lesson-panel"><div><span id="lessonCount">Experiment 1 of 6</span><h2 id="lessonTitle">Freeze a moving voltage</h2><p id="lessonInstruction">Watch the input move while each trigger captures one value.</p></div><div class="lesson-actions"><button id="previousLesson">Previous</button><button id="nextLesson">Next experiment</button></div></section>
<section class="lab-grid">
<aside class="controls" aria-label="Laboratory controls">
<h2>Signal</h2>
<label>Input source<select id="source"><option value="lfo">LFO</option><option value="noise">Noise</option><option value="manual">Manual CV</option></select></label>
<label id="manualRow" hidden>Manual voltage<input id="manual" type="range" min="-5" max="5" step=".01" value="0"><output id="manualOut">0.00 V</output></label>
<fieldset><legend>Hold behaviour</legend><label><input type="radio" name="mode" value="sample-hold" checked> Sample & Hold</label><label><input type="radio" name="mode" value="track-hold"> Track & Hold</label><label><input type="radio" name="mode" value="companion-hold"> Companion Hold</label></fieldset>
<label>Clock / gate rate<input id="rate" type="range" min=".1" max="4" step=".1" value="1"><output id="rateOut">1.0 Hz</output></label>
<label>Slew<input id="slew" type="range" min="0" max="1" step=".01" value=".35"><output id="slewOut">35%</output></label>
<label>Timing jitter<input id="jitter" type="range" min="0" max=".35" step=".01" value=".1"><output id="jitterOut">10%</output></label>
<label>Companion spread<input id="spread" type="range" min=".1" max="2" step=".1" value="1"><output id="spreadOut">1.0 V</output></label>
<h2>Pitch teaching</h2>
<label>0 V reference<select id="reference"><option value="130.812783">C3 · 130.81 Hz</option><option value="220" selected>A3 · 220 Hz</option><option value="261.625565">C4 · 261.63 Hz</option><option value="440">A4 · 440 Hz</option></select></label>
<label class="toggle"><input id="quantize" type="checkbox"> Quantize to semitones</label>
<label>Time scale<select id="timeScale"><option value="1">Normal</option><option value=".25">Slow · ¼ speed</option><option value=".1">Very slow · ⅒ speed</option></select></label>
<div class="button-row"><button id="trigger" class="primary">Trigger now</button><button id="pause">Pause</button><button id="step">Step once</button><button id="reset">Reset</button></div>
</aside>
<main class="workbench">
<section class="scope-card">
<div class="scope-heading"><div><p class="eyebrow">Shared event timeline</p><h2>Voltage and event evidence</h2></div><div class="live-values"><span>Input<b id="inputValue">0.00 V</b></span><span>Held<b id="heldValue">0.00 V</b></span><span>Output<b id="outputValue">0.00 V</b></span></div></div>
<canvas id="scope" width="1100" height="430" tabindex="0" aria-label="Interactive voltage timeline. Click to place measurement cursors."></canvas>
<div class="scope-tools"><button id="cursorA">Place cursor A</button><button id="cursorB">Place cursor B</button><button id="clearCursors">Clear cursors</button><output id="cursorReadout">Click the graph after choosing a cursor.</output></div>
<div class="legend"><span class="input">Input</span><span class="raw">Captured target</span><span class="output">Slewed output</span><span class="companions">Companions</span><span class="event">Trigger / gate edge</span></div>
</section>
<section class="explanation"><p class="eyebrow">What just happened?</p><h2 id="eventTitle">Waiting for the first event</h2><p id="eventText">The input is moving. A trigger will capture its current voltage.</p></section>
<section class="hear"><div><p class="eyebrow">1 V per octave audio</p><h2>Hear the control paths</h2><p>Each +1 V doubles frequency. Quantizer mode rounds voltage to one of twelve semitones per volt.</p></div><div class="pitch-grid"><output id="lowPitch">Low silent</output><output id="centrePitch">Centre 0.00 V · A3 · 220 Hz</output><output id="highPitch">High silent</output></div><div class="voice-controls"><div data-voice="low"><b>Low</b><button data-action="mute">Mute</button><button data-action="solo">Solo</button></div><div data-voice="centre"><b>Centre</b><button data-action="mute">Mute</button><button data-action="solo">Solo</button></div><div data-voice="high"><b>High</b><button data-action="mute">Mute</button><button data-action="solo">Solo</button></div></div><div class="audio-actions"><output id="audioStatus">Audio stopped</output><button id="audioStart">Start audio</button><button id="audioStop">Panic / stop</button></div></section>
</main></section>`;

const $=<T extends Element>(selector:string):T=>{const el=document.querySelector<T>(selector);if(!el)throw new Error(`Missing ${selector}`);return el};
const canvas=$<HTMLCanvasElement>('#scope');const ctx=canvas.getContext('2d');if(!ctx)throw new Error('Canvas unavailable');
const source=$<HTMLSelectElement>('#source'),manual=$<HTMLInputElement>('#manual'),manualRow=$<HTMLElement>('#manualRow'),rate=$<HTMLInputElement>('#rate'),slewInput=$<HTMLInputElement>('#slew'),jitter=$<HTMLInputElement>('#jitter'),spread=$<HTMLInputElement>('#spread'),reference=$<HTMLSelectElement>('#reference'),quantize=$<HTMLInputElement>('#quantize'),timeScale=$<HTMLSelectElement>('#timeScale');
const lessons=[
['Freeze a moving voltage','Watch the input move while each trigger captures one value.','lfo','sample-hold',1,0,0,1],
['Hear exact 1 V/octave','Start audio. A one-volt rise doubles the centre frequency.','manual','sample-hold',1,0,0,1],
['Turn steps into glides','Raise slew and hear the output travel between held targets.','noise','sample-hold',1.2,.72,0,1],
['Compare tracking with sampling','Track & Hold follows while its gate is open, then freezes.','lfo','track-hold',.6,.1,0,1],
['Compare continuous and quantized CV','Toggle semitone quantization and hear smooth voltage become stepped musical pitch.','lfo','sample-hold',1.5,.15,0,1],
['Hear and isolate companions','Use mute and solo to compare low, centre and high voices around one sampled value.','noise','companion-hold',1,.3,.08,1]
] as const;
let mode:HoldMode='sample-hold',inputSource:Source='lfo',raw=0,smoothed=0,gate=false,nextEvent=0,lastTime=0,lessonIndex=0,noise=0,paused=false,pendingStep=false;
let audio:AudioContext|null=null,master:GainNode|null=null,voices:Voice[]=[];
const history:Point[]=[];const muted:Record<VoiceName,boolean>={low:false,centre:false,high:false};let solo:VoiceName|null=null;
let cursorMode:'a'|'b'|null=null,cursorA:number|null=null,cursorB:number|null=null;

function inputAt(t:number){if(inputSource==='manual')return Number(manual.value);if(inputSource==='noise'){noise+=(Math.random()*10-5-noise)*.16;return noise}return Math.sin(t/820)*3.8+Math.sin(t/2300)*.45}
function referenceHz(){return Number(reference.value)}
function audibleCv(cv:number){return quantizeCv(cv,quantize.checked)}
function describe(cv:number){const q=audibleCv(cv),f=cvToFrequency(q,referenceHz());return `${q.toFixed(2)} V · ${frequencyToNoteName(f)} · ${f<1000?f.toFixed(1):(f/1000).toFixed(2)+' k'}Hz`}
function explain(kind:string,input:number){const title=$<HTMLElement>('#eventTitle'),text=$<HTMLElement>('#eventText');if(mode==='track-hold'){title.textContent=gate?'Gate opened: tracking':'Gate closed: holding';text.textContent=gate?`The output is following the changing input, now ${input.toFixed(2)} V.`:`The gate closed and holds ${raw.toFixed(2)} V.`;return}if(mode==='companion-hold'){const c=companionValues(raw,Number(spread.value));title.textContent='Three related values captured';text.textContent=`Low ${c.low.toFixed(2)} V, centre ${raw.toFixed(2)} V and high ${c.high.toFixed(2)} V. Solo each voice to compare them.`;return}title.textContent=kind==='manual'?'Manual trigger captured the input':'Clock trigger captured the input';text.textContent=`Captured ${raw.toFixed(2)} V${quantize.checked?`; audio rounds it to ${audibleCv(raw).toFixed(2)} V`:''}.`}
function fire(t:number,kind='clock'){const input=inputAt(t);if(mode==='track-hold'){gate=!gate;if(!gate)raw=input}else raw=sampleHold(raw,input,true);explain(kind,input)}
function schedule(t:number){nextEvent=t+jitteredInterval((1000/Number(rate.value))/Number(timeScale.value),Number(jitter.value),Math.random())}
function syncVoiceMix(){if(!audio||voices.length!==3)return;const names:VoiceName[]=['low','centre','high'];names.forEach((name,i)=>{const permitted=mode==='companion-hold'||name==='centre';const selected=!solo||solo===name;const gain=permitted&&selected&&!muted[name]?(name==='centre'?.022:.016):0;voices[i].gain.gain.setTargetAtTime(gain,audio!.currentTime,.02)});$<HTMLOutputElement>('#audioStatus').value=mode==='companion-hold'?'Audio running · companion voices':'Audio running · centre voice'}
function updateReadouts(input:number,c:{low:number;high:number}){$<HTMLElement>('#inputValue').textContent=`${input.toFixed(2)} V`;$<HTMLElement>('#heldValue').textContent=`${raw.toFixed(2)} V`;$<HTMLElement>('#outputValue').textContent=`${smoothed.toFixed(2)} V`;$<HTMLOutputElement>('#centrePitch').value=`Centre ${describe(smoothed)}`;$<HTMLOutputElement>('#lowPitch').value=mode==='companion-hold'?`Low ${describe(c.low)}`:'Low silent';$<HTMLOutputElement>('#highPitch').value=mode==='companion-hold'?`High ${describe(c.high)}`:'High silent'}
function line(values:number[],colour:string,top:number,height:number){ctx.strokeStyle=colour;ctx.lineWidth=2;ctx.beginPath();values.forEach((v,i)=>{const x=58+i*(canvas.width-82)/219,y=top+height/2-(v/5)*(height*.42);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.stroke()}
function cursorDetails(index:number){const p=history[index];if(!p)return'No sample';return `#${index+1}: input ${p.input.toFixed(2)} V · held ${p.raw.toFixed(2)} V · output ${p.output.toFixed(2)} V`}
function updateCursorReadout(){const parts=[];if(cursorA!==null)parts.push(`A ${cursorDetails(cursorA)}`);if(cursorB!==null)parts.push(`B ${cursorDetails(cursorB)}`);if(cursorA!==null&&cursorB!==null)parts.push(`Δ ${Math.abs(cursorB-cursorA)} frames`);$<HTMLOutputElement>('#cursorReadout').value=parts.join(' | ')||'Click the graph after choosing a cursor.'}
function render(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#101821';ctx.fillRect(0,0,canvas.width,canvas.height);const lanes=[['CLOCK / GATE',20,55],['INPUT',92,90],['CAPTURED TARGET',202,80],['SLEWED OUTPUT',302,90]] as const;ctx.font='12px system-ui';ctx.fillStyle='#b9c5ce';lanes.forEach(([name,top,height])=>{ctx.fillText(name,12,top+14);ctx.strokeStyle='#2d3b47';ctx.strokeRect(58,top,canvas.width-82,height)});history.forEach((p,i)=>{const x=58+i*(canvas.width-82)/219;if(p.gate){ctx.fillStyle='rgba(110,180,150,.16)';ctx.fillRect(x,20,5,55)}if(p.event){ctx.strokeStyle='#f4c96b';ctx.beginPath();ctx.moveTo(x,20);ctx.lineTo(x,392);ctx.stroke()}});line(history.map(p=>p.input),'#79c8ff',92,90);line(history.map(p=>p.raw),'#f4c96b',202,80);line(history.map(p=>p.output),'#f1f3f5',302,90);if(mode==='companion-hold'){line(history.map(p=>p.high),'#d98cff',302,90);line(history.map(p=>p.low),'#7ee0b8',302,90)};[[cursorA,'#ff7b7b','A'],[cursorB,'#7bffb1','B']].forEach(([index,colour,label])=>{if(typeof index!=='number')return;const x=58+index*(canvas.width-82)/219;ctx.strokeStyle=String(colour);ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,18);ctx.lineTo(x,398);ctx.stroke();ctx.fillStyle=String(colour);ctx.fillText(String(label),x+4,16)})}
function advance(t:number){if(!lastTime){lastTime=t;schedule(t)}const scaled=t*Number(timeScale.value),input=inputAt(scaled);let event=false;if(t>=nextEvent){fire(scaled);event=true;schedule(t)}if(mode==='track-hold')raw=trackHold(raw,input,gate);smoothed=slew(smoothed,raw,Number(slewInput.value));const c=companionValues(smoothed,Number(spread.value));history.push({input,raw,output:smoothed,high:c.high,low:c.low,event,gate});if(history.length>220){history.shift();if(cursorA!==null)cursorA=Math.max(0,cursorA-1);if(cursorB!==null)cursorB=Math.max(0,cursorB-1)}render();updateReadouts(input,c);if(audio&&voices.length===3){const now=audio.currentTime;voices[0].osc.frequency.setTargetAtTime(cvToFrequency(audibleCv(c.low),referenceHz()),now,.03);voices[1].osc.frequency.setTargetAtTime(cvToFrequency(audibleCv(smoothed),referenceHz()),now,.03);voices[2].osc.frequency.setTargetAtTime(cvToFrequency(audibleCv(c.high),referenceHz()),now,.03)}lastTime=t}
function frame(t:number){if(!paused||pendingStep){advance(t);pendingStep=false}requestAnimationFrame(frame)}
function reset(){history.length=0;raw=0;smoothed=0;gate=false;noise=0;nextEvent=0;lastTime=0;cursorA=cursorB=null;updateCursorReadout();$<HTMLElement>('#eventTitle').textContent='View reset';$<HTMLElement>('#eventText').textContent='The next event begins fresh evidence.'}
function syncLabels(){$<HTMLOutputElement>('#manualOut').value=`${Number(manual.value).toFixed(2)} V`;$<HTMLOutputElement>('#rateOut').value=`${Number(rate.value).toFixed(1)} Hz`;$<HTMLOutputElement>('#slewOut').value=`${Math.round(Number(slewInput.value)*100)}%`;$<HTMLOutputElement>('#jitterOut').value=`${Math.round(Number(jitter.value)*100)}%`;$<HTMLOutputElement>('#spreadOut').value=`${Number(spread.value).toFixed(1)} V`;manualRow.hidden=inputSource!=='manual'}
function applyLesson(index:number){lessonIndex=(index+lessons.length)%lessons.length;const [title,instruction,src,newMode,newRate,newSlew,newJitter,newSpread]=lessons[lessonIndex];inputSource=src;source.value=src;mode=newMode;rate.value=String(newRate);slewInput.value=String(newSlew);jitter.value=String(newJitter);spread.value=String(newSpread);document.querySelectorAll<HTMLInputElement>('input[name="mode"]').forEach(i=>i.checked=i.value===mode);$<HTMLElement>('#lessonCount').textContent=`Experiment ${lessonIndex+1} of ${lessons.length}`;$<HTMLElement>('#lessonTitle').textContent=title;$<HTMLElement>('#lessonInstruction').textContent=instruction;syncLabels();syncVoiceMix();reset()}
function createVoice(panValue:number):Voice{if(!audio||!master)throw new Error('Audio unavailable');const osc=audio.createOscillator(),gain=audio.createGain();gain.gain.value=0;const pan=typeof audio.createStereoPanner==='function'?audio.createStereoPanner():null;if(pan){pan.pan.value=panValue;osc.connect(gain).connect(pan).connect(master)}else osc.connect(gain).connect(master);osc.start();return{osc,gain,pan}}
async function startAudio(){if(audio)return;audio=new AudioContext();master=audio.createGain();master.gain.value=.7;master.connect(audio.destination);voices=[createVoice(-.5),createVoice(0),createVoice(.5)];syncVoiceMix()}
function stopAudio(){voices.forEach(v=>{try{v.osc.stop()}catch{}v.osc.disconnect();v.gain.disconnect();v.pan?.disconnect()});voices=[];master?.disconnect();void audio?.close();audio=null;master=null;$<HTMLOutputElement>('#audioStatus').value='Audio stopped'}

source.onchange=()=>{inputSource=source.value as Source;syncLabels();reset()};manual.oninput=syncLabels;[rate,slewInput,jitter,spread,timeScale].forEach(el=>el.oninput=()=>{syncLabels();reset()});reference.onchange=()=>updateReadouts(inputAt(performance.now()),companionValues(smoothed,Number(spread.value)));quantize.onchange=()=>updateReadouts(inputAt(performance.now()),companionValues(smoothed,Number(spread.value)));
document.querySelectorAll<HTMLInputElement>('input[name="mode"]').forEach(i=>i.onchange=()=>{mode=i.value as HoldMode;syncVoiceMix();reset()});
$<HTMLButtonElement>('#trigger').onclick=()=>fire(performance.now(),'manual');$<HTMLButtonElement>('#pause').onclick=()=>{paused=!paused;$<HTMLButtonElement>('#pause').textContent=paused?'Resume':'Pause'};$<HTMLButtonElement>('#step').onclick=()=>{paused=true;pendingStep=true;$<HTMLButtonElement>('#pause').textContent='Resume'};$<HTMLButtonElement>('#reset').onclick=reset;$<HTMLButtonElement>('#previousLesson').onclick=()=>applyLesson(lessonIndex-1);$<HTMLButtonElement>('#nextLesson').onclick=()=>applyLesson(lessonIndex+1);$<HTMLButtonElement>('#learnTab').onclick=()=>{$<HTMLElement>('#lessonPanel').hidden=false};$<HTMLButtonElement>('#exploreTab').onclick=()=>{$<HTMLElement>('#lessonPanel').hidden=true};$<HTMLButtonElement>('#audioStart').onclick=startAudio;$<HTMLButtonElement>('#audioStop').onclick=stopAudio;
document.querySelectorAll<HTMLButtonElement>('.voice-controls button').forEach(button=>button.onclick=()=>{const container=button.closest<HTMLElement>('[data-voice]');if(!container)return;const voice=container.dataset.voice as VoiceName;if(button.dataset.action==='mute'){muted[voice]=!muted[voice];button.classList.toggle('selected',muted[voice]);button.textContent=muted[voice]?'Unmute':'Mute'}else{solo=solo===voice?null:voice;document.querySelectorAll<HTMLButtonElement>('[data-action="solo"]').forEach(b=>b.classList.toggle('selected',b.closest<HTMLElement>('[data-voice]')?.dataset.voice===solo))}syncVoiceMix()});
$<HTMLButtonElement>('#cursorA').onclick=()=>cursorMode='a';$<HTMLButtonElement>('#cursorB').onclick=()=>cursorMode='b';$<HTMLButtonElement>('#clearCursors').onclick=()=>{cursorA=cursorB=null;updateCursorReadout();render()};canvas.onclick=e=>{if(!cursorMode||!history.length)return;const rect=canvas.getBoundingClientRect(),x=(e.clientX-rect.left)*(canvas.width/rect.width),index=Math.max(0,Math.min(history.length-1,Math.round((x-58)*219/(canvas.width-82))));if(cursorMode==='a')cursorA=index;else cursorB=index;cursorMode=null;updateCursorReadout();render()};window.addEventListener('pagehide',stopAudio);
applyLesson(0);requestAnimationFrame(frame);
